# Generated by Django 5.0.3 on 2024-03-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_type',
            new_name='type',
        ),
    ]
